version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: fishprice
      POSTGRES_USER: fishuser
      POSTGRES_PASSWORD: DBPASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fishuser -d fishprice" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./historical_data.xlsx:/data/historical_data.xlsx
      - ./backend/models:/app/models
    environment:
      DATABASE_URL: postgresql://postgres.htzymlxthcxndpylrbol:lqYnc4xCP6pv1pvP@aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres
      CORS_ORIGINS: http://localhost:3000

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: [ "npm", "run", "dev", "--", "-H", "0.0.0.0", "-p", "3000" ]
    depends_on:
      - backend

volumes:
  postgres_data:
