'use client';

import { useState } from 'react';
import { FileText, Download, Loader2 } from 'lucide-react';

interface ForecastRow {
  day: number;
  dateLabel: string;
  prediction: number;
  confidence: number;
  lower: number | null;
  upper: number | null;
}

interface Props {
  forecast?: ForecastRow[];
}

export default function ProcurementReportButton({ forecast }: Props) {
  const [loading, setLoading] = useState(false);

  const handleDownload = async () => {
    setLoading(true);
    try {
      // Generate a text-based procurement report client-side
      const today = new Date().toLocaleDateString('en-LK', { 
        weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' 
      });
      
      const forecastRows = forecast && forecast.length > 0 ? forecast : [
        { day: 1, dateLabel: 'Day 1', prediction: 950, confidence: 30, lower: 920, upper: 980 },
        { day: 2, dateLabel: 'Day 2', prediction: 975, confidence: 35, lower: 940, upper: 1010 },
        { day: 3, dateLabel: 'Day 3', prediction: 990, confidence: 40, lower: 950, upper: 1030 },
      ];

      const avg = Math.round(forecastRows.reduce((s, d) => s + d.prediction, 0) / forecastRows.length);
      const minPrice = Math.min(...forecastRows.map(d => d.prediction));
      const maxPrice = Math.max(...forecastRows.map(d => d.prediction));

      const reportLines = [
        '═══════════════════════════════════════════════════════════',
        '          SMART PROCUREMENT REPORT — FishPrice.LK',
        '═══════════════════════════════════════════════════════════',
        '',
        `  Report Date  : ${today}`,
        `  Fish Species : Balaya (White Tuna)`,
        `  Market       : Peliyagoda Wholesale Fish Market`,
        `  Model        : XGBoost + LightGBM Ensemble (RMSE: 26.31)`,
        '',
        '───────────────────────────────────────────────────────────',
        '  3-DAY PRICE FORECAST',
        '───────────────────────────────────────────────────────────',
        '',
        ...forecastRows.map(d =>
          `  Day ${d.day} (${d.dateLabel})`.padEnd(22) +
          `Rs. ${d.prediction.toLocaleString()}`.padEnd(16) +
          `± ${d.confidence} Rs  ` +
          (d.lower && d.upper ? `[${d.lower} – ${d.upper}]` : '')
        ),
        '',
        '───────────────────────────────────────────────────────────',
        '  PROCUREMENT INTELLIGENCE',
        '───────────────────────────────────────────────────────────',
        '',
        `  3-Day Average Price  : Rs. ${avg.toLocaleString()} per kg`,
        `  Price Range          : Rs. ${minPrice.toLocaleString()} – Rs. ${maxPrice.toLocaleString()}`,
        `  Spread               : Rs. ${(maxPrice - minPrice).toLocaleString()}`,
        '',
        '  ✔ RECOMMENDATION:',
        `     Best procurement window is Day 1 (lowest forecast: Rs. ${minPrice.toLocaleString()}).`,
        '     Consider bulk purchase on lowest-forecast day to minimize cost.',
        '',
        '───────────────────────────────────────────────────────────',
        '  RISK FACTORS',
        '───────────────────────────────────────────────────────────',
        '',
        '  • Seasonal demand: Poya holiday periods increase demand 10–15%.',
        '  • Weather impact: SW monsoon may disrupt coastal landings.',
        '  • Fuel prices: Recent increases may raise transport costs.',
        '',
        '───────────────────────────────────────────────────────────',
        '  DISCLAIMER',
        '───────────────────────────────────────────────────────────',
        '',
        '  Forecasts are AI-generated estimates and should not be the',
        '  sole basis for financial decisions. Actual prices may vary.',
        '',
        '═══════════════════════════════════════════════════════════',
        '  Generated by FishPrice.LK  |  fishprice.lk',
        '═══════════════════════════════════════════════════════════',
      ];

      const reportText = reportLines.join('\n');
      const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `procurement_report_balaya_${new Date().toISOString().split('T')[0]}.txt`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);
    } catch (err) {
      console.error(err);
      alert('Failed to generate report. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <button
      onClick={handleDownload}
      disabled={loading}
      className="glass glass-hover"
      style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '0.75rem',
        padding: '1rem 1.5rem',
        borderRadius: '0.875rem',
        color: '#EDF4FF',
        border: '1px solid rgba(100, 180, 255, 0.15)',
        cursor: 'pointer',
        fontSize: '0.9rem',
        fontWeight: 600,
        transition: 'all 0.2s',
        width: '100%',
        background: 'rgba(255, 255, 255, 0.03)',
      }}
    >
      <div style={{
        width: '32px', height: '32px',
        borderRadius: '8px',
        background: 'rgba(0, 212, 255, 0.1)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        color: '#00D4FF'
      }}>
        {loading ? <Loader2 size={18} className="animate-spin" /> : <FileText size={18} />}
      </div>
      <div style={{ textAlign: 'left', flex: 1 }}>
        <div style={{ fontSize: '0.875rem' }}>Smart Procurement Report</div>
        <div style={{ fontSize: '0.7rem', color: '#4A6285', fontWeight: 500 }}>Download weekly digest (.txt)</div>
      </div>
      <Download size={16} color="#4A6285" />
    </button>
  );
}
